export const fontImport =
  "@import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;0,9..144,700;1,9..144,500&family=Karla:wght@400;500;600;700&display=swap');";

export const styles = {
  page: { minHeight: "100vh", background: "#EEF0E6", fontFamily: "'Karla', sans-serif", color: "#26312B", paddingBottom: 40 },
  authPage: { minHeight: "100vh", background: "#EEF0E6", fontFamily: "'Karla', sans-serif", color: "#26312B", display: "flex", alignItems: "center", justifyContent: "center", padding: 20 },
  authCard: { background: "#FFFFFF", border: "1px solid #DEDAC8", borderRadius: 12, padding: "28px 24px", width: "100%", maxWidth: 360 },
  authEyebrow: { fontSize: 12, letterSpacing: 0.4, color: "#6b7268", marginBottom: 2 },
  authTitle: { fontFamily: "'Fraunces', serif", fontWeight: 600, fontSize: 24, margin: "0 0 18px" },
  field: { display: "flex", flexDirection: "column", gap: 4, marginBottom: 12 },
  label: { fontSize: 12.5, fontWeight: 600, color: "#6b7268" },
  input: { border: "1px solid #DEDAC8", borderRadius: 6, padding: "9px 10px", fontSize: 14, background: "#FBFAF5", fontFamily: "'Karla', sans-serif" },
  passwordToggle: { position: "absolute", right: 8, top: "50%", transform: "translateY(-50%)", border: "none", background: "transparent", color: "#6b7268", cursor: "pointer", padding: 4, display: "flex" },
  primaryBtn: { width: "100%", background: "#4B6350", color: "#fff", border: "none", borderRadius: 6, padding: "10px", fontSize: 14, fontWeight: 700, cursor: "pointer", marginTop: 6 },
  linkBtn: { background: "transparent", border: "none", color: "#4B6350", fontSize: 12.5, fontWeight: 600, cursor: "pointer", padding: 0, textDecoration: "underline" },
  authFooter: { display: "flex", justifyContent: "space-between", marginTop: 14, flexWrap: "wrap", gap: 8 },
  errorText: { color: "#8A4B52", fontSize: 12.5, marginTop: -4, marginBottom: 8 },
  messageText: { color: "#4B6350", fontSize: 12.5, marginTop: -4, marginBottom: 8 },

  header: { padding: "24px 20px 12px", display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: 12 },
  eyebrow: { fontSize: 12, letterSpacing: 0.4, color: "#6b7268", marginBottom: 2 },
  h1: { fontFamily: "'Fraunces', serif", fontWeight: 600, fontSize: 26, margin: 0, color: "#26312B", display: "flex", alignItems: "center", gap: 8 },
  viewingSelect: { fontFamily: "'Fraunces', serif", fontWeight: 600, fontSize: 19, color: "#26312B", border: "1px solid #DEDAC8", borderRadius: 8, padding: "5px 8px", background: "#fff" },
  renameIconBtn: { border: "none", background: "transparent", color: "#a3a08f", cursor: "pointer", display: "flex", padding: 2 },
  renameInput: { fontFamily: "'Fraunces', serif", fontWeight: 600, fontSize: 22, border: "1px solid #DEDAC8", borderRadius: 6, padding: "3px 8px", background: "#fff" },
  logoutBtn: { border: "1px solid #DEDAC8", background: "#fff", color: "#6b7268", borderRadius: 8, padding: "8px 12px", fontSize: 12.5, fontWeight: 600, cursor: "pointer" },
  tabs: { display: "flex", gap: 4, padding: "0 20px", borderBottom: "1px solid #DEDAC8", marginTop: 8 },
  tabBtn: { border: "none", background: "transparent", fontFamily: "'Karla', sans-serif", fontSize: 14, fontWeight: 600, color: "#6b7268", padding: "10px 6px", cursor: "pointer", borderBottom: "2px solid transparent", marginRight: 16 },
  tabBtnActive: { color: "#26312B", borderBottom: "2px solid #C98A3D" },
  backLink: { display: "flex", alignItems: "center", gap: 4, border: "none", background: "transparent", color: "#6b7268", fontSize: 13, fontWeight: 600, cursor: "pointer", padding: "0 0 12px", marginTop: -6 },
  main: { padding: "18px 20px 0" },
  errorBanner: { margin: "0 20px", padding: "8px 12px", background: "#F5E3E1", color: "#8A4B52", fontSize: 13, borderRadius: 6 },
  updateBanner: { margin: "0 20px 12px", padding: "10px 12px", background: "#EAF0EA", color: "#4B6350", fontSize: 12.5, fontWeight: 600, borderRadius: 8, display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8 },
  timeline: { background: "#FFFFFF", border: "1px solid #DEDAC8", borderRadius: 10, overflow: "hidden" },
  phraseCard: { border: "1px solid #E8CFA0", background: "#FBF3E4", borderRadius: 10, padding: "14px 16px", marginBottom: 14 },
  phraseText: { fontFamily: "'Fraunces', serif", fontStyle: "italic", fontSize: 14.5, color: "#8A6A2E", margin: 0, lineHeight: 1.5 },
  dailyMacroCard: { border: "1px solid #DEDAC8", background: "#FFFFFF", borderRadius: 10, padding: "14px 16px", marginBottom: 14 },
  dailyMacroTitle: { fontFamily: "'Fraunces', serif", fontWeight: 600, fontSize: 14, color: "#26312B", marginBottom: 8 },
  dailyMacroRow: { display: "flex", justifyContent: "space-between", gap: 8, flexWrap: "wrap" },
  dailyMacroItem: { fontSize: 13, color: "#4B6350" },
  timelineWrap: { padding: "16px 18px" },
  timelineHeadRow: { display: "flex", gap: 10, alignItems: "flex-start" },
  timeCol: { minWidth: 56, display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 3, paddingTop: 2 },
  timeText: { fontSize: 12, color: "#8A4B52", fontWeight: 700 },
  mealHeadBtn: { display: "flex", alignItems: "center", justifyContent: "space-between", flex: 1, minWidth: 0, border: "none", background: "transparent", cursor: "pointer", padding: 0, textAlign: "left" },
  mealName: { fontFamily: "'Fraunces', serif", fontSize: 17, fontWeight: 600 },
  mealBody: { marginTop: 10 },
  optionChips: { display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 8 },
  chip: { fontSize: 12, fontWeight: 600, padding: "4px 10px", borderRadius: 20, border: "1px solid #DEDAC8", background: "#F7F5EC", color: "#6b7268", cursor: "pointer" },
  chipActive: { background: "#4B6350", borderColor: "#4B6350", color: "#fff" },
  ingList: { margin: 0, padding: 0, listStyle: "none" },
  ingItem: { display: "flex", gap: 6, fontSize: 14, color: "#3c463f", padding: "3px 0" },
  approxGrams: { color: "#a3a08f", fontSize: 12.5, fontStyle: "italic" },
  macroSummary: { display: "flex", flexWrap: "wrap", gap: 10, fontSize: 12.5, color: "#4B6350", background: "#EAF0EA", borderRadius: 6, padding: "6px 6px", marginTop: 8 },
  macroIncomplete: { color: "#a3a08f", fontStyle: "italic", fontSize: 11.5 },
  ingQty: { color: "#3c463f", fontWeight: 700, fontSize: 13.5, whiteSpace: "nowrap" },
  emptyMeal: { fontSize: 13, color: "#a3a08f", fontStyle: "italic", margin: 0 },
  mealObs: { fontSize: 12.5, color: "#8A4B52", marginTop: 6, marginBottom: 0 },
  planObsBox: { background: "#FFFFFF", border: "1px solid #DEDAC8", borderRadius: 10, padding: 16, marginTop: 16 },
  planObsHead: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  planObsTitle: { fontFamily: "'Fraunces', serif", fontWeight: 600, fontSize: 15, marginBottom: 8, display: "block" },
  planObsText: { fontSize: 13.5, color: "#3c463f", margin: 0, lineHeight: 1.5 },
  textarea: { width: "100%", border: "1px solid #DEDAC8", borderRadius: 6, padding: 8, fontSize: 13.5, resize: "vertical", background: "#FBFAF5" },
  rowGap: { display: "flex", gap: 8, marginTop: 8, alignItems: "center" },
  smallBtnPrimary: { display: "flex", alignItems: "center", gap: 5, background: "#4B6350", color: "#fff", border: "none", borderRadius: 6, padding: "6px 10px", fontSize: 12.5, fontWeight: 600, cursor: "pointer" },
  smallBtn: { display: "flex", alignItems: "center", gap: 5, background: "transparent", color: "#6b7268", border: "1px solid #DEDAC8", borderRadius: 6, padding: "6px 10px", fontSize: 12.5, fontWeight: 600, cursor: "pointer" },
  iconBtn: { border: "none", background: "transparent", color: "#6b7268", cursor: "pointer", padding: 4, display: "flex", alignItems: "center" },
  addMealBtn: { display: "flex", alignItems: "center", gap: 6, width: "100%", justifyContent: "center", background: "#FFFFFF", border: "1px dashed #C3BFA9", borderRadius: 10, padding: "12px", fontSize: 13.5, fontWeight: 600, color: "#4B6350", cursor: "pointer", marginTop: 12 },
  mealEditorBox: { background: "#FFFFFF", border: "1px solid #DEDAC8", borderRadius: 10, marginBottom: 10, overflow: "hidden" },
  mealEditorHead: { display: "flex", alignItems: "center", gap: 8, padding: "10px 12px" },
  expandBtn: { border: "none", background: "transparent", color: "#6b7268", cursor: "pointer", display: "flex" },
  mealNameInput: { flex: 1, fontFamily: "'Fraunces', serif", fontSize: 15, fontWeight: 600, border: "none", background: "transparent", minWidth: 0 },
  timeInput: { border: "1px solid #DEDAC8", borderRadius: 6, fontSize: 12.5, padding: "4px 6px", width: 92, background: "#FBFAF5" },
  mealEditorBody: { padding: "0 12px 14px", display: "flex", flexDirection: "column", gap: 8 },
  obsInput: { width: "100%", border: "1px solid #DEDAC8", borderRadius: 6, padding: "7px 9px", fontSize: 12.5, background: "#FBFAF5" },
  optionBox: { border: "1px solid #E4E1D2", borderRadius: 8, background: "#FBFAF5" },
  optionHead: { display: "flex", alignItems: "center", gap: 8, padding: "8px 10px" },
  optionNameInput: { flex: 1, fontSize: 13.5, fontWeight: 600, border: "none", background: "transparent", minWidth: 0 },
  ingCount: { fontSize: 11, color: "#a3a08f" },
  optionBody: { padding: "0 10px 10px", display: "flex", flexDirection: "column", gap: 6 },
  ingRow: { display: "flex", gap: 6, alignItems: "center" },
  ingNameInput: { flex: 1, border: "1px solid #E4E1D2", borderRadius: 6, padding: "6px 8px", fontSize: 12.5, minWidth: 0, background: "#fff" },
  ingQtyInput: { width: 54, border: "1px solid #E4E1D2", borderRadius: 6, padding: "6px 6px", fontSize: 12.5, background: "#fff" },
  ingUnitInput: { border: "1px solid #E4E1D2", borderRadius: 6, padding: "6px 4px", fontSize: 12.5, background: "#fff" },
  addIngBtn: { display: "flex", alignItems: "center", gap: 5, alignSelf: "flex-start", background: "transparent", border: "none", color: "#4B6350", fontSize: 12, fontWeight: 600, cursor: "pointer", padding: "4px 0" },
  nutritionBox: { background: "#fff", border: "1px solid #E4E1D2", borderRadius: 6, padding: 8, marginBottom: 6 },
  nutritionGrid: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)", gap: 8 },
  nutritionField: { fontSize: 11, color: "#6b7268", fontWeight: 600, display: "flex", flexDirection: "column", gap: 3, minWidth: 0 },
  nutritionInput: { border: "1px solid #DEDAC8", borderRadius: 6, padding: "7px 8px", fontSize: 13, background: "#FBFAF5", width: "100%", minWidth: 0, boxSizing: "border-box" },
  suggestionBtn: { display: "block", width: "100%", textAlign: "left", background: "#FBF3E4", border: "1px solid #E8CFA0", color: "#8A6A2E", borderRadius: 6, padding: "8px 10px", fontSize: 12, fontWeight: 600, cursor: "pointer", marginBottom: 8, lineHeight: 1.4 },
  contributeBtn: { display: "flex", alignItems: "center", gap: 5, width: "100%", justifyContent: "center", background: "transparent", border: "1px dashed #C3BFA9", color: "#4B6350", borderRadius: 6, padding: "7px 8px", fontSize: 11.5, fontWeight: 600, cursor: "pointer", marginTop: 8 },
  addOptionBtn: { display: "flex", alignItems: "center", gap: 5, justifyContent: "center", border: "1px dashed #C3BFA9", borderRadius: 8, padding: "8px", fontSize: 12.5, fontWeight: 600, color: "#4B6350", background: "transparent", cursor: "pointer" },
};

export const UNITS = ["g", "kg", "ml", "l", "unidade", "colher", "chávena"];
